hibernate.connection.username=PDC
hibernate.connection.password=PDC
hibernate.connection.driver_class=org.apache.derby.iapi.jdbc.AutoloadedDriver

hibernate.dialect=org.hibernate.community.dialect.DerbyDialect

hibernate.current_session_context_class=thread

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true


hibernate.hbm2ddl.auto=update
hibernate.hbm2ddl.create_schemas=true
hibernate.default_schema=PDC
